import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { GazeLiveOverlayProvider } from "@/components/gaze-live-overlay-provider";
import { NotificationProvider } from "@/hooks/use-global-notifications";
import "./globals.css";
import { html } from "framer-motion/client";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NotificationProvider>
          <GazeLiveOverlayProvider>{children}</GazeLiveOverlayProvider>
        </NotificationProvider>
      </body>
    </html>
  );
}
